image:
  # This image is built upon the following Dockerfile: .gitpod.Dockerfile
  #ghcr.io/lpiot/gitpod-workspace:test
  # You can dynamically build the image when you create a new GitPod workspace with the following lines
  #gitpod/workspace-full
  lpiot/gitpod-python312:v0.1
  # file: .gitpod.Dockerfile
